### PR TITLE
Added a reroll command

### PR DESCRIPTION
**Pull request by todasj**
I was reading this issue with an alternative word for rerolling a character, a more modern game language
https://github.com/Meridian59/Meridian59/issues/660

This change however only adds an alternative command, the old suicide still exists and in some text it still refers to the word "suicide" and "kill youself". Creating this pull request to start a discussion about it, should we keep the suicide command or remove it, shoud we alter any other texts or prompts like this one: 
bild
bild

### CODE REVIEW

**Comment by akirmse** [comment]
I don't have any objection to a synonym.  Anyone else?

**Comment by adrienlaws** [comment]
I think this is a nice suggestion to modernize the language a bit and keep it focused on game/RPG terminology.  Reroll sounds great and is what I have noticed people say when they talk about restarting their character.
> I will reroll this character to try something different.
> I rerolled my character because his statistics didn't make sense.

You might consider renaming the default titles and buttons to use "reroll" instead of "suicide," and leave in the suicide command for historical purposes. 

In any case, +1 from Toko!

**Comment by davidklaw** [comment]
No objections here 👍🏻

**Comment by todasj** [comment]
> I think this is a nice suggestion to modernize the language a bit and keep it focused on game/RPG terminology. Reroll sounds great and is what I have noticed people say when they talk about restarting their character.
> 
> > I will reroll this character to try something different.
> > I rerolled my character because his statistics didn't make sense.
> 
> You might consider renaming the default titles and buttons to use "reroll" instead of "suicide," and leave in the suicide command for historical purposes.
> 
> In any case, +1 from Toko!

I was thinking exacly about those changes, to change the title to "Meridian Character Reroll", the text to "Performing a reroll will destroy..." and the button to "Reroll"

@akirmse What do you say, should this be changed or just add "reroll" as an alternative command?

**Comment by Meridian59** [comment]
That sounds fine.

**Comment by Aesica** [comment]
No objections at all.  To add to this, related dialog should be updated to exclude self-harm language and encourage the use of "reroll" over "suicide."

"Performing a character reroll will destroy your character..."
"You aren't ready to reroll yet, as you've only just begun this life.  Give it a day."

Seal of approval! :)

**Comment by jrotunda** [comment]
Thanks @todasj, this looks good.

**Pull request merged**
