### PR TITLE
Ammo fix Nerudite/Silver Arrows

### PR DESCRIPTION
**Pull request by Nagath**
Nerudite Arrows haven't been shattering because BaseDamage wasn't
passing who and target. Silver Arrows also weren't doing double damage
to undead.

### CODE REVIEW

**Comment by Koveras** [comment]
+1

**Comment by Meridian59** [comment]
It looks like this might cause some runtime error messages in GoldSword because it doesn't have these parameters, and it should.  Could you please add those to goldswrd.kod:GetBaseDamage?  Then I'll merge this.

**Comment by davidklaw** [comment]
@Meridian59 It looks like the requested changes were made. Might this be ready for a merge?

**Comment by akirmse** [comment]
Yes, I think this is only other instance of GetBaseDamage, so it should be safe.

**Pull request merged**
