### PR TITLE
Rented rooms for Ko'catan

### PR DESCRIPTION
**Pull request by Gar103v2**
This commit adds rentable rooms to Ko'catan in the same style as the
Barloque and Marion rooms. It also adds island textures that default
match the island style. Those textures are also available as choices in
Barloque and Marion.

This commit also fixes a rare initialization issue with rented rooms,
where if the default bed position was equal to 1, it would not be lifted
or textured.

This commit also fixes a debug error in statistics - rented rooms are
not in the list of rooms to have their 'number of times entered'
counted, so there's no need to check RIDs over 10000. This should
prevent a debug message happening every single time someone enters a
rented room.

### CODE REVIEW

**Comment by Gar103v2** [comment]
I should add, it appears there is a popup window saying 'the game has changed, download new files yes/no' every time someone enters a rented room with their key. This is happening for all rented rooms, and I haven't been able to determine why. Usually that popup window occurs with some resource mismatch, but I haven't seen any strings or strange objects that might cause it. I could take a look at that in another pull request.

**Comment by qorkod** [comment]
Please merge, this is a highly requested feature (Ko'catan Rooms) and even mentioned as a design goal for the Ko'catan/Revelations update but time and resources were limited.

The code checks out for the text prompts from Moxal and updated Ko'catan Inn room resources for entering the doors.

It could probably go for more textures from the Island style (blue, green and yellow wood panelling) but as-is would be a good starting point to get them functional.

**"This commit also fixes a debug error in statistics - rented rooms are
not in the list of rooms to have their 'number of times entered'
counted, so there's no need to check RIDs over 10000. This should
prevent a debug message happening every single time someone enters a
rented room."**

The debug message occurs on 101 and 102. Any time a new room is created and entered, a user will get the debug message pop-up, **which causes a crash** if the user selects "Yes". To recreate all you have to do is rent a room at any inn and enter it for the first time.

**Comment by davidklaw** [comment]
I pulled this down to test and found the following issue to occur when entering each of the Aerie Guest House rentable doors. For comparison, I tested the doors in the Limping Toad Tavern and did not have this issue.

image

I'm happy to continue testing this once someone can help me figure this one out 😆

**Comment by akirmse** [comment]
Make sure that you have this kocrent.roo in your client resource subdirectory.  roo files must always match on the server and client (there's a rudimentary security check to prevent some hacking).

**Comment by davidklaw** [comment]
Maybe I'm missing other steps to set up my environment? This is what I see upon entering.

image

**Comment by akirmse** [comment]
The change description says "It also adds island textures" but it then doesn't actually include any textures.

**Comment by skittles1** [comment]
The original PR for this was https://github.com/OpenMeridian/Meridian59/pull/1030 and you can grab the missing wall texture from https://github.com/OpenMeridian/Meridian59/blob/master/resource/graphics/delerium/kocatanroom/grd50078.bgf. The Island floor texture is already in the client, used elsewhere in Island rooms.

**Comment by davidklaw** [comment]
I placed `grd50078.bgf` in my resource folder and the issue of black walls remains. I'm going to move on to other issues and PRs and wait for updates _and_ a clear test plan.

**Comment by davidklaw** [comment]
I remain stuck on the failing wallpaper here and would appreciate any sort of direction. This is the debug message I'm seeing:

> Couldn't load bitmap for grid type 50078

I've placed both `grd50078.bgf` in `grd50078.bmp` in `run/localclient/resource/` to no avail.

It seems clear this PR still has some issues to work through, but it's been 2 years 🤷‍♂️

**Comment by akirmse** [comment]
That means the client can't load grd50078.bgf.  I guess triple-check that it's in the right directory.

One other thing you could try is renaming grd50078.bgf to some other bgf in the resource directory (backing that one up first of course), e.g. some wall texture in Tos, and see if it loads.  I seem to remember that there's some power-of-2 width restriction on bitmaps that maybe the forks have done away with.  What are the dimensions of the bmp file?

**Comment by davidklaw** [comment]
I grabbed the BMP from the path @skittles1 mentioned above. It's 360x256. It seems to be something with the BGF file. I copied and renamed `grd50077.bgf` to `grd50078.bgf` and it renders.

**Comment by akirmse** [comment]
Maybe the forks changed the bgf format in a non-backward-compatible way?  If you have the bmp, you can build the bgf yourself (see the resource/textures directory and its makefile).

**Comment by davidklaw** [comment]
Bingo!

image

This at least allows me to move forward with testing, but I wouldn't know the right way to update the makefile. I got by with the following:

```
BGFS = \
	$(OUTDIR)\grd20121.bgf \
	$(OUTDIR)\grd20122.bgf \
	$(OUTDIR)\grd20124.bgf \
	$(OUTDIR)\grd20125.bgf \
	$(OUTDIR)\grd20126.bgf \
	$(OUTDIR)\grd20127.bgf \
	$(OUTDIR)\grd20128.bgf \
	$(OUTDIR)\grd20129.bgf \
	$(OUTDIR)\grd20130.bgf \
	$(OUTDIR)\grd50078.bgf \  <---
```

```
$(OUTDIR)\grd50078.bgf:
	$(MAKEBGF) -o $@ -n "kocatan" -s 4 1 $** 1 1 1
```

**Comment by akirmse** [comment]
Yep, you got it.  The -n "kocatan" is the name of the texture shown in the room editor.  Set it to something humans would recognize.  Spaces are allowed in the name.

I don't remember what the -s parameter does.  The code says it's the "shrink factor", which I think was used to get higher resolution on things like faces.  It's probably not used for wall textures.  You could try setting it to 1 and see if it still looks OK.

**Comment by davidklaw** [comment]
Right on 👍 I guess I'll build on this to drop another PR soon.

**Comment by jrotunda** [comment]
This can be closed now with the texture, functionality and text issues addressed in #392 checked in for a future merge.

**Comment by davidklaw** [comment]
@Meridian59 Can be closed in favor of #392

**Pull request closed without merging**
