### PR TITLE
Add new Item - Light Disciple Robe

### PR DESCRIPTION
**Pull request by Nagath**
Added new Item Light Disciple Robe and added them to Avar Shaman loot

### CODE REVIEW

**Comment by Arkblade** [comment]
What purpose do these serve? ...and I mean other than being sleeveless. =)

**Comment by Arkblade** [comment]
Personally ... I think these robes should weigh half as much as Disciple Robes, offer 5 less spellpower to the dedicated school but offer NO spellpower to any other school. My opinion.

**Comment by Nagath** [comment]
I made them in this version really lighter ^^
30 less weight, +3SP per level for the dedicated school (to a max of 15), +2SP to all others.
My Intension here was to let them weight less but also let them give less Power so they have their own purpose in Inventory Management (More other stuff but less power for one school)

**Comment by Arkblade** [comment]
Cool beans

**Comment by Nagath** [comment]
I added them as loot to Avar Shamans, I think would be more interessting to not let Orc wizards alone drop all kinds of Robes ^^

**Pull request closed without merging**
