### PR TITLE
Add monster sounds for living statue, dark angel

### PR DESCRIPTION
**Pull request by Nagath**
originaly by skittles1

These sounds appear to be missing on all copies of the game. Used the Lich attack sound for dark angel, and the ghost aggro and death sounds. Used xeo sounds for living statue.

### CODE REVIEW

**Comment by Meridian59** [comment]
I can't find stat1awr.wav.  Can you please include it?

**Comment by Nagath** [comment]
Sorry was a mistype by me

**Comment by Nagath** [comment]
Mayhem created some sound for Dark Angels and mailed them to me so I put them in here :)
They sound great!

**Comment by Meridian59** [comment]
Looks like dangel.kod is now missing from the change?

**Comment by Nagath** [comment]
Thats because the new Dark Angel Soundfiles have the same names like the originally in dangel.kod used but not existent .wav files.

**Comment by jrotunda** [comment]
I can't wait to hear this in-game!  :)  The sounds were made in Adobe Premier and are from home-recorded audio, not free-ware and no copyright issue (just excited to give voice to the DA! :+1:

**Pull request merged**
