### PR TITLE
Adds new quest for Jala shield insignia quest

### LINKED ISSUE #712: Quest: Jala Insignia Herald Shield Quest is missing from Parrin (Minstrel)
Parrin (minstrel.kod) is missing his unique quest to allow a player to get a Jala Insignia for their Herald Shield.

References:

In Blakston.Kod:

Quest Id Flags:    INSIG_JALA;
               }
if IsClass(poDestNPC,&Minstrel)
               {
                  iInsignia = INSIG_JALA;

**In minstrel.kod, INSIG_JALA is missing from properties.**

Expectation:

If a Player with a Herald Shield in their personal Inventory says, "Tithe", they'll get a quest from Parrin to dedicate their shield with the Jala Insignia.

_Currently, this Insignia can only be accessed by Admin/DM creation only._

### PR DESCRIPTION
**Pull request by davidklaw**
This PR introduces a new quest for Parrin that lets players earn a Jala insignia for their herald shield. The quest is modeled after the priestess insignia quests, requiring players to collect Jala-inspired items, and includes messaging that reflects Parrin’s distinct personality.

Currently, the Jala insignia is unintentionally very rare, only obtainable through the CV crate at extremely low odds. Even if this rarity wasn’t intentional, it created an unnecessary barrier for players. From what I understand, the original intent was to make this insignia available through gameplay, and this update helps fulfill that goal.

Screenshot 2024-08-28 221428

Closes #712

### CODE REVIEW

**Comment by davidklaw** [comment]
> How did players get Jala shields before - was it admin only / cv crate?

By admin only.

**Comment by Aesica** [comment]
> How did players get Jala shields before - was it admin only / cv crate?

Pretty sure it's both.   I'm almost certain they could also rarely appear from the CV crate.

**Comment by ZaviusEJ** [comment]
Awesome that you were able to add this on! I had similar coding but couldn't get it to work in my dev environment.

Disagree with the idea that its worked fine before this. Making Jala less of a mule school involves making it more accessible to everyone. Adding this quest helps inch Jala forward as a real school. Nice work!

**Comment by jrotunda** [comment]
Let's get this in there. If I die tomorrow and there's no DM, there will be no one to generate Jala Heralds in game. You'd be looking at 1 Herald a year from that CV crate (the chance of finding a herald in the crate is already 1/100, the chance of it being pre-dedicated to Jala even less). They cost a huge tithe to dedicate from a teacher, and it's not new content - this is content that was already coded and written, and a couple lines of code were missing to connect the quest to the teacher (Parrin) - this is merely fixing something already intended. I specifically brought this up as an issue because I saw that it was supposed to be in-game for decades. We have plenty of other rare things. Let the Jala mages have their damn herald.

**Comment by davidklaw** [comment]
Bumping after updating the PR description to reflect our conversation. Currently, the odds of acquiring a Jala insignia are extremely low, making it unintentionally rare. This change aligns its availability with other schools and addresses what is considered a missing feature.

**Pull request merged**
