### PR TITLE
Texture fix for east ende

### PR DESCRIPTION
**Pull request by TheDiggie**
fix floating textures above adventure hall and bank sign

### CODE REVIEW

**Comment by TheDiggie** [comment]
https://github.com/Meridian59/Meridian59/issues/425

**Comment by davidklaw** [comment]
@TheDiggie I'm relatively new to map editing here and since there's no great way to compare, could you clue me into how you resolved this? Was it just adjusting these two x offset values?

image

**Comment by davidklaw** [comment]
Visually, these changes look good to me 👍 

Screenshots using the new room files:
image

image

image

image

**Comment by TheDiggie** [comment]
@davidklaw unfortunately for this one i do not have a good answer. the floating texture isnt on any of the walls so technically shouldn't be there at all. i added the offset because the sign needs it, if u look next to the wall by the sign u can see where it starts to repeat. after i set the offset the floating texture simply isnt there anymore. no idea why :p

**Comment by davidklaw** [comment]
Ah, okay. That makes sense. A good PR would include what you just shared so that we can double-check the updated position of the sign (I was only focused on the issue in the sky). Thanks for knocking these two issues out. There's a bunch more calling your name 😉

**Pull request closed without merging**
