### PR TITLE
Update castle2d.roo

### PR DESCRIPTION
**Pull request by Dirhai**
### What this PR make?

> It fixs the light bug we have in castle2d.roo

### How can i test this?

> First you need to add the new castle2d.roo in the run/localclient/resources, load the server (the blue arrow in the server window)  now go to the Royal Library of the Bourgeois Castle and cast darkness, the entire room should be dark now, with the old file some sectors aren't affect by light/darkness spells.

Original:

castle2d before darkness

castle2d before darkness pt2

Fixed:

castle2d fixed darkness pt2

castle2d fixed darkness

### CODE REVIEW

**Comment by davidklaw** [comment]
I tested and confirmed the changes. I can't help but admire the small detail of light on the ceiling and thinking it should also be on the floor.

One thing I noticed was that these 3 wall surfaces remain dim when others are light.
Screenshot 2022-07-21 201641

The ceiling details:
Screenshot 2022-07-21 201647

The ceiling details remain in the dark:
Screenshot 2022-07-21 201737

I don't think this is related to the changes in this PR, but this branch is giving me the following errors, where these objects are `TokenGame` and `TerritoryGame`, not `RentableRoom`.

```
Jul 21 2022 20:14:39 | Fatal: Class hash bin 97983 has length 2; Increase SizeClassHash in [Memory] in blakserv.cfg
Jul 21 2022 20:14:39 | AddResource can't add resource num 23286 because it already exists!
Jul 21 2022 20:14:39 | AddResource can't add resource num 23287 because it already exists!
Jul 21 2022 20:14:39 | AddResource can't add resource num 23288 because it already exists!
Jul 21 2022 20:14:39 | Cannot open banned log file banned.txt
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 24 of OBJECT 3468 CLASS Room (10012)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 25 of OBJECT 3468 CLASS Room (10012)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 26 of OBJECT 3468 CLASS Room (10012)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 27 of OBJECT 3468 CLASS Room (10012)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 28 of OBJECT 3468 CLASS Room (10012)
...
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 9 of OBJECT 3508 CLASS RentableRoom (10626)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 14 of OBJECT 3508 CLASS RentableRoom (10626)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 15 of OBJECT 3508 CLASS RentableRoom (10626)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 13 of OBJECT 3508 CLASS RentableRoom (10626)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 39 of OBJECT 3508 CLASS RentableRoom (10626)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 40 of OBJECT 3508 CLASS RentableRoom (10626)
Jul 21 2022 20:14:39 | SetObjectProperties can't set invalid property 41 of OBJECT 3508 CLASS RentableRoom (10626)
```

**Comment by Dirhai** [comment]
The light detail in the ceiling was not added by me, this detail was already in the original file, and it should still be there when darkness is casted to give the impression that even with darkness the outside light dont stop to enter in the room,  this detail on the ceiling already is mirroed on the floor but because the dark color of the floor its almost unoticiable.

**Comment by akirmse** [comment]
If it looks OK walking around, it's probably OK.

Since this is a resource change, it would require a client update, so I think we don't want this in the main branch yet.

**Comment by davidklaw** [comment]
I wonder if it's a good time to replace `master` with `release` and `development` branches? This repo can be updated to use `development` as the default contributors pull from and push to.

**Comment by davidklaw** [comment]
@Dirhai I think you may have unintentionally merged in #372

**Comment by Dirhai** [comment]
> @Dirhai I think you may have unintentionally merged in #372 
Dang sorry, I'm still learning how to use this, going to fix later.

**Comment by Dirhai** [comment]
The unintentional merge with #372 was reverted. @davidklaw

**Comment by jrotunda** [comment]
This is ready for review.

I appreciate @Dirhai took the time to fix this on request and confident of how it should look, I want to clarify resolution on two notes brought up so this can move forward as it's a solid and tight fix not needing further tampering.

There should be - and is - a sliver of light on the ceiling and floor from the partially drawn curtains in the library, a specific detail in the original design by Q. The light shines onto where the Meridian Timeline history lore book is.

The darker texture by the wall @davidklaw pointed out is intended, Dirhai is correct that this texture is for the Mocker's Tower which is a separate structure. 

The graphic bug was seen while updating lighting effects in some areas, @Dirhai learned the room editor to help - and is correct in their understanding of the room lighting and texture design. 

Their keen attention to detail in ambience and information presented through the design work of Meridian is what inspired me to even be in that room, casting darkness while doing a global light value/sun height/angle check. Thank you @Dirhai!

**Pull request merged**
