### PR TITLE
Conveyance

### PR DESCRIPTION
**Pull request by Nagath**
by M59Gar, nearly 1 year online on 103
"Utility Spell that sends any stack of number items that can be stored in a vault to your closest personal vault. Can't be used on money."

Little adjustments: Now need 5 Mana + 2 Vigor, not automaticaly on every char but has to be bought from Bei Naq. Still Kraanan Level 1

### CODE REVIEW

**Comment by jrotunda** [comment]
+1

**Comment by Koveras** [comment]
+1

**Comment by XYLUM** [comment]
+1

**Comment by Meridian59** [comment]
I think this changes the original game too drastically.

**Pull request closed without merging**
