### PR TITLE
Adding correct resistance to ants

### PR DESCRIPTION
**Pull request by todasj**
The plResistances for ants in ant.kod used "-ATCK_WEAP_ALL", the "-" is only used for spell resistance, to distinguish them from weapon resistance.

This is the ResistanceCheck-function, it checks if the iResType is larger or smaller than 0 to know if it is a resistance to weapon type or resistance to a spell type. 

```
   ResistanceCheck(atype = 0, aspell = 0)
   "Given bitvectors of attack type and spell, find the resistance modifier "
   "which applies. Largest resistance plus worst weakness gives the modifier."
   {
      local j, iResType, iMaxRes, iMinRes, iResistance;

      iMaxRes = NO_RESISTANCE;
      iMinRes = NO_RESISTANCE;

      for j in plResistances
      {
         iResType = Nth(j,2);
         if iResType > 0   
         {
            % It's a resistance to weapon type

            if (atype & iResType) <> 0
               OR (atype <> 0 AND iResType = ATCK_WEAP_ALL)
            {
               iResistance = Nth(j,1);
               
               if iResistance > iMaxRes
               {
                  iMaxRes = iResistance;
               }

               if iResistance < iMinRes
               {
                  iMinRes = iResistance;
               }
            }
         }
         else
         {
            % It's a resistance to spell type
            iResType = -iResType;

            if (aspell & iResType) <> 0
               OR (aspell <> 0 AND iResType = ATCK_SPELL_ALL)
            {
               iResistance = Nth(j,1);
               
               if iResistance > iMaxRes
               {
                  iMaxRes = iResistance;
               }

               if iResistance < iMinRes
               {
                  iMinRes = iResistance;
               }
            }
         }
      }

      % clip to max/min values
      iMaxRes = bound(iMaxRes,$,MAX_RESISTANCE);
      iMinRes = bound(iMinRes,MIN_RESISTANCE,$);

      return iMaxRes + iMinRes;
   }
```

I changed it to "ATCK_WEAP_ALL".

### CODE REVIEW

**Comment by todasj** [comment]
After some struggle to revert my changes, this PR will now fix the ants resistance.

@akirmse I guess I better ask you, is there any interest if I clean up plResistances and sort them more in spell type and weapon type or is it just a waste of time?

**Comment by akirmse** [comment]
I think we have much more important things to do than reordering lists.

Thanks for the bug fix!

**Comment by davidklaw** [comment]
👏🏻 @todasj

**Comment by davidklaw** [comment]
@todasj It's hard to tell from the description here, but is the result of this change that ants are now properly resistant to weapon attacks?

**Pull request merged**
