### PR TITLE
Numeric damage and Healing output and streamlined combat messages + minor Bug Fixes

### PR DESCRIPTION
**Pull request by Serpentiel-zz**
Out of the 103 Repo with fixes coded by MorbusM59

### CODE REVIEW

**Comment by jrotunda** [comment]
PLEASE let's get this added.  This would be fun to have as well as helpful to know weapon and healing damage, and get players more interested in their character's gear and skills.  

Nice Jala Herald Shield bug fix. 

 I think the damage to trolls line should stay in there.  That seems like intentionally wrong misinformation from the description that will make a player have an unpleasant troll encounter.  Even if it isn't - it's legend at this point! : )

**Comment by Koveras** [comment]
Please add this. There is little I'd want to see more.

**Comment by davidklaw** [comment]
Big PR that's now out of date. Seems like the numeric damage messages might not be desired?

Three of the proposed changes included in this have already been merged: 
- #308 
- #309 
- #310 

If there's not a desire to add numeric damage messages or update the axe's description, this seems ready to close. If they are, I move to close this and leave any notes that could help a future contributor pick those up and push them forward.

**Comment by akirmse** [comment]
Agreed, small changes are better anyway.  This one is much too large.

**Pull request closed without merging**
