### PR TITLE
Added Compile Script and LocalClient Runner

### PR DESCRIPTION
**Pull request by Thorbenn**
- Added a compile PowerShell Script which should make it easier to compile DEBUG and RELEASE Versions of Meridian 59 Classic Client and Server
- Added a small PowerShell Script that runs the Client in Localhost Mode, instead of modifiying it over a shortcut

### CODE REVIEW

**Comment by davidklaw** [comment]
Neat script @Thorbenn ! A script like this could be a nice thing to have. @Meridian59 Is this sort of script something you're open to including with the codebase or is a script like this best maintained elsewhere and linked to from some documentation, like an eventual GitHub wiki perhaps?

**Comment by akirmse** [comment]
I think it would have to be clearer what the script does---it's called "compile" but it looks like it doesn't build everything, for example the Blakod?  I'm not a Powershell user myself.  We also would want to put this in a subdirectory somewhere, not at the top level.

**Comment by davidklaw** [comment]
Beyond simply compiling, this looks to be a complete build and release script. It will compile, copy client resources (from a given source), package releases -- it bundles up the few separate tasks. @Meridian59 I'm thinking this probably won't get revised, so it's a good candidate for closing. But if anyone out there is using PowerShell, this is a nice user-friendly script to check out.

**Comment by Thorbenn** [comment]
Hello Everyone, sorry for the late reply. 
Basically what the Script does, is automate all steps that are listed in the instructions document to provide a fully functioning Client and Server, both separately zipped to make it easier for the Deployment Process.  The script does trigger a compilation, by calling the nmake build with the debug or release parameter. Anything defined in the nmake Build will be built :)

Instead of manually triggering the compilation and then copying over all the required client files (Images, Sounds, etc.), why not have it all fully automated and reproducible. 

That was the idea behind the script.

**Comment by akirmse** [comment]
Sure, if this is moved into a new top-level directory called "contrib", and
maybe fix some of the typos in the comments, I'll take it.

**Comment by davidklaw** [comment]
Hell yeah @Thorbenn, better late than never 😄 Do you have any interest in revisiting this PR to rename and move it around? I don't know exactly where it should go, but that I'm happy to test and review it again.

**Comment by Thorbenn** [comment]
Absolutely! Let me fix the Typos and move the scripts to the directory contrib as Andrew suggested.
I will setup a fresh copy of Windows and VS to do the changes. So it might take a day or two ;)

**Comment by davidklaw** [comment]
Maybe this could be moved to a `/scripts` folder? Or `/dev-tools`? We could add a README in there with something like:

# Dev Tools
This is a collection of utilities used for BlakSton/Meridian 59 internal development.
They aren't used by the applications directly.

## Windows PowerShell Scripts
Converted the Post Build Batch for Meridian 59 to PowerShell and extended it with some neat tweaks.

**Comment by davidklaw** [comment]
And while we're talking about it, I launch my dev environment using the `launchdevcmd` batch script that comes with Visual Studio Community 2022. As a result, I can't take advantage of PowerShell scripts, or at least I don't know how to. If I don't and use your scripts, `nmake` is unavailable. I'd be interested in using your scripts but don't know how. I'd be curious to know if you have any thoughts on this.

**Comment by akirmse** [comment]
I thought "contrib" would be better because we don't know what other types of things will be contributed, if anything.  If it's "scripts" and then someone uploads a nice icon, hm, I guess we can't put that in scripts, so yet another top-level directory?

**Comment by Thorbenn** [comment]
I can understand the argument from both sides. But maybe it would be smart to have an area dev-tools and put all new dev tools and scripts there?

@davidklaw Regarding nmake, you must use the Developer PowerShell for VS 2022. You can open it directly from your IDE under Tools -> Command Line -> Developer PowerShell or you can open it from the Shortcut which is placed in the Visual Studio Start Menu Entry. There is a Shortcut for the Developer PowerShell in it as well. 
I mostly trigger all my Windows/VS related Builds over the Developer PowerShell or when working with other Tools over a Unix Command Line Tool. The Console is always my preferred choice :)

**Comment by akirmse** [comment]
Please put it in contrib.  If lots of people start using it or we get a lot more helpful scripts, we can always move it easily.

**Comment by Thorbenn** [comment]
Okay, ignore my current Push. will rename the folder asap :)

**Comment by Thorbenn** [comment]
Folder is renamed to contrib :)

**Comment by davidklaw** [comment]
@Thorbenn with the save!

Image

**Pull request merged**
