### PR TITLE
Dusk rat mask

### PR DESCRIPTION
**Pull request by TheDiggie**

### CODE REVIEW

**Comment by davidklaw** [comment]
Description? Screenshots?

**Comment by TheDiggie** [comment]
https://gyazo.com/56dbcaac7d9c28400ed87fff4405d2df

image

**Comment by akirmse** [comment]
The description should explain why a change exists.  What is this for?

**Comment by TheDiggie** [comment]
Well. I don't have a "reason" for it. Its just a mask I made that fits the meridian theme and style to expand on the available mask we have. Same goes for the troll mask. It's a purely cosmic item that players love

**Comment by akirmse** [comment]
OK.  Closing this as I think it's already possible to get better art through an in-game color translation.

For future reference we'd rather have the original art checked in, instead of the post-processed .bgfs.

**Pull request closed without merging**
