### PR TITLE
Migrate RoomEditor to VS2013/OWLNext (PART I)

### PR DESCRIPTION
**Pull request by cyberjunk**
This is PART I from:
https://github.com/Meridian59/Meridian59/pull/324

It only contains the first commit (14fc309) from the pullrequest with OWL sources (directory owl-6.34)...

Alternatively, here's a download link for the same owl-6.34 folder (which you could just extract and commit yourself): https://drive.google.com/open?id=0B-6rsj6uHlolLUhhUFRkQXdyM1k&authuser=0

### CODE REVIEW

**Comment by cyberjunk** [comment]
Anything wrong with this or are you just lacking time? :-)

Let me know if you want the roomeditor vs2013 migration restructured any other way.
I think I remember you requested PART I (plain OWL sources first) like this...

**Comment by Meridian59** [comment]
I can't take this change because it has an unrelated change to user.kod in
it.  I'll download the zip myself and then move to the next part.

**Comment by cyberjunk** [comment]
>> I can't take this change because it has an unrelated change to user.kod in
it.

I think just merging this pullrequest may modify the contributed LoC statistics inappropriately anways...

I have have some idea what you are refering to with the user.kod change, is it the flags unsetting of DRAWFX_BLACK to fix the wholist? I might have accidentally built this pullrequest on top of a branch I used for this fix... anyways tis here is so huge, it's a pain to review it here on github anways.

Once you merged this manually, I can make a new pullrequest with PART II on top of your new master...

**Comment by Meridian59** [comment]
I've checked in the OWL sources, so I'm closing this.  Going to look at getting it to build next.

**Pull request closed without merging**
