### PR TITLE
Fix flip signs and floating lines in Barloque North and South (barln.roo and barls.roo)

### PR DESCRIPTION
**Pull request by Dirhai**
fffff
wwwww
sign1
sign2

### CODE REVIEW

**Comment by akirmse** [comment]
This change looks empty?

I think it should be possible to have no transparent artifacts here though.

**Comment by Dirhai** [comment]
Yes it really looks empty, but atleast easier to hide, and no more floating line. I will look again tomorrow those room, the only thing i can do to hide it using the room editor is creating another wall infront of the gap🤷

**Comment by akirmse** [comment]
What I mean is, there appear to be no files in this PR.

**Comment by Dirhai** [comment]
Sorry, i think the files are there now.

**Comment by akirmse** [comment]
Hm, I don't know about this... I feel like a more complete fix is possible with more room editor experience.

**Comment by Dirhai** [comment]
Makes sense i will return to those rooms later, i dont like to creating new sectors and walls to avoid new bugs, i feel like the room editor are very sensitive lol

**Comment by davidklaw** [comment]
These floating lines can be resolved using the new "no horizontal tiling" option added in #583. Sorry @Dirhai, but I think this can be closed _or_ updated using the new room editor capabilities.

**Comment by akirmse** [comment]
I'm going to close this, since the new flag is a better way to fix this.

**Pull request closed without merging**
